stages:
  - buildimage

variables:
  CI_REGISTRY: images.paas.redhat.com
  CI_REGISTRY_REPO: osci/rpminspect

image build:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: buildimage
  tags:
    - docker
  before_script:
    - mkdir -p /kaniko/.docker
    - cat "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor
      --skip-tls-verify
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination ${CI_REGISTRY}/${CI_REGISTRY_REPO}:${CI_COMMIT_SHORT_SHA}
      --destination ${CI_REGISTRY}/${CI_REGISTRY_REPO}:latest

merge request image build:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: buildimage
  tags:
    - docker
  before_script:
    - mkdir -p /kaniko/.docker
    - cat "$DOCKER_AUTH_CONFIG" >  /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor
      --skip-tls-verify
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination ${CI_REGISTRY}/${CI_REGISTRY_REPO}:mr-${CI_MERGE_REQUEST_IID}
      --destination ${CI_REGISTRY}/${CI_REGISTRY_REPO}:mr-${CI_MERGE_REQUEST_IID}-${CI_COMMIT_SHORT_SHA}
