---
include:
  - project: osci/deployments/ci-deployment-templates
    file: build-upload-image-template.yml

variables:
  CI_REGISTRY_REPO: rpminspect
  DOCKERFILE_PATH: $CI_PROJECT_DIR/Dockerfile.rhel

build-and-upload-image:
  extends: .build-and-upload-image

mr-build-and-upload-image:
  extends: .mr-build-and-upload-image
